### ISSUE TITLE
When using Bool flag '--no' is not shown in help.

### ISSUE THREAD

**Issue by rmb938** [alecthomas/kingpin#216] opened 2017-11-04 23:24 UTC
When using a Bool flag the `--no` option is not shown in the help text. This could be a bit confusing to end users since there is no indication on how to use it.

If the flag is set to required it shows in the usage but not under flags.

Example:

```
./bin/deli region update --help
usage: deli region update --[no-]schedulable <region ID>

Flags:
      --help         Show context-sensitive help (also try --help-long and
                     --help-man).
  -d, --debug        Debug logging.
      --api-server="http://localhost:8080"
                     Sandwich Cloud API Server [Env: DELI_API_SERVER]
      --raw          Show raw json output
      --schedulable  Enable or disable the ability to schedule workloads in the
                     region

Args:
  <region ID>  The region ID
```

**Comment by alecthomas** [comment] 2017-11-05 00:03
This is fixed in v3-unstable. Can you give it a try and report back?

**Comment by rmb938** [comment] 2017-11-05 00:18
Yea, give me a bit. Seems like the action api was changed so I need to fix some things.

**Comment by rmb938** [comment] 2017-11-05 00:31
It does not seem to be fixed in v3-unstable

```
./bin/deli region update --help
usage: deli [<flags>] region [<flags>] update --[no-]schedulable <region ID>

Flags:
      --help         Show context-sensitive help.
  -d, --debug        Debug logging.
      --api-server="http://localhost:8080"
                     Sandwich Cloud API Server [Env: DELI_API_SERVER]
      --raw          Show raw json output
      --schedulable  Enable or disable the ability to schedule workloads in the
                     region

Args:
  <region ID>  The region ID
```

also that branch seems to be missing some flag types.

**Comment by alecthomas** [comment] 2017-11-05 00:40
The `--no-` prefix should only show up when the flag default is inverted. Is that not sufficient?

File related flag types were removed due to file descriptor leaks.

**Comment by rmb938** [comment] 2017-11-05 00:56
It is also missing the IP flags.

No matter what I set the default to it still only shows the flag without `--no-`. And that would be sufficient however when the flag is set to required it can be a bit confusing to the end user, seeing `--no-` in the usage part of the help text but not under flags.

**Comment by rmb938** [comment] 2017-11-05 01:15
Also when the flag is required and not provided the error says

```
 required flag --schedulable not provided
```

without the `--no-`

**Comment by alecthomas** [comment] 2017-11-05 05:29
> It is also missing the IP flags.

Ah, that looks like it got nuked accidentally when I removed some other types with unfortunate semantics. I'll add that back in.

> Just to add my use case if it will help why I want this. My CLI app is a frontend for an api. The api allows setting a schedulable boolean on an entity and the user can toggle it between true and false. The CLI wont know the state of the entity before the command is run and all error checking is done on the api side. So having both options --schedulable and --no-schedulable in the help text makes sense because there is no default that I can set ahead of time to show one vs the other.

Okay, that makes some sense. Also configuration files are now supported with the new resolver API, and if the configuration file sets a bool flag the user would currently not have a way to unset it (and vice versa).

> No matter what I set the default to it still only shows the flag without --no-. And that would be sufficient however when the flag is set to required it can be a bit confusing to the end user, seeing --no- in the usage part of the help text but not under flags.

Okay, just got home. That looks like a regression. Instead of fixing it, I think I'll implement always having `[no-]` in the help.

**Comment by rmb938** [comment] 2017-11-05 14:23
Ok, great! Any timeline on when v3 will be released?

**Closed** 2017-11-06 01:18 UTC

**Comment by alecthomas** [comment] 2017-11-06 01:20
Okay, so to get the `--no-flag` behaviour you will now have to use `NegatableBool()`.

> Ok, great! Any timeline on when v3 will be released?

Not exactly, but you can subscribe to #90 to track its progress.

The two major outstanding items are `Help "sections".` and `Making sequences optionally support being comma-separated lists.`.
